### ISSUE TITLE
Problem starting in Windows

### ISSUE THREAD

**Issue by samlown** [trinidad/trinidad_init_services#1]
Hi, I've managed to get a Rails app under Trinidad on a Windows 2003 SP2 machine without too much hastle, but I'm un-able to work out how to get the Windows Daemon to load correctly.

After installing the trinidad_daemon gem, I've run "jruby -S trinidad_daemon_install", provided the path to Rails project root, didn't add any options, and used the auto-detected Java path.

The service gets added to the list, but when I try to start it, the funny loading bar pops up for a few moments and disappears. Nothing gets loaded in the background. Looking at the Windows events log, I can see that there is an entry accounting for the fact the application didn't load, which goes something like this (translated from spanish):

```
Applcation with errors: prunsrv.exe, version: 1.0.5.0, module with error: jvm.dll, version 11.3.0.2, error address 0x0014327a.
```

And thats about all I can find out :-( When looking at the properties popup of the Trinidad service, I can't see any options at all that specifiy the location or properties of the service to load up, just the follwowing command:

c:/jruby-1.6.0/lib/ruby/1.8/gems/trinidad_daemon-0.4.1//trinidad-libs/prunsrv.exe //RS/Trinidad

¿any idea where I might be able to find more details to try and debug this?

Many thanks! 
sam

**Comment by samlown** [comment]
Hi,

Okay, managed to get it working after a bit more investigation. The key to debugging is to download and run the [commons daemon's](http://commons.apache.org/daemon/procrun.html) prunmgr with //ES//Trinidad. That brings up a fancy configuration interface to let you tell it where to output the logs to. Getting the log in the proper place helped considerably.

After that, I discovered that the "-e production" argument hadn't been added. Took me a while to realise that arguments need to be separated with returns rather than spaces in the arguments list box.

Starting the service manually from the console also makes things easier as the output is sent direct to STDOUT: prunsrv //TS//Trinidad  Using this I managed to discover that the --config option must be supplied with an = and the full path for it to load correctly.

Along the way, I came across this very useful utility from Microsoft http://technet.microsoft.com/en-us/sysinternals/bb896653.aspx that allows you to see a more complete list of the processes running and kill them if needed. An instance of prunsrv.exe ghosted and without this app I'd probably have had to reboot or something. Didn't come up in the Task Manager at all.

I hope this helps someone else survive Windows!

**Comment by rurounijones** [comment]
In light of this ticket and the comments on @ec8a1e98325ace4b7ad25489d88466c0853bb131 maybe this should be reopened and looked at.

**Comment by scottlowe** [comment]
I have removed the lines that overwrite the default production configuration setting during Windows service configuration.

I can confirm that the Trinidad Windows service installs and starts in production mode on Windows 7 under JRuby 1.6.1 (1.8 & 1.9 Ruby compat mode) as expected.

https://github.com/trinidad/trinidad_init_services/commit/6501a8ea85f904e09d2a8e78133c4d9be1889e31
