### ISSUE TITLE
Add an uninstaller

### ISSUE THREAD

**Issue by driehle** [trinidad/trinidad_init_services#22]
[Feature request]

It would be really cool to have some kind of uninstaller in trinidad_init_services. On UNIX platforms the uninstallation process seems to be simply removing the `/etc/init.d/trinidad` file. However on windows, you need the prunsrv.exe for the uninstallation. Therefore it would be cool if there was an option like `trinidad_init_service --uninstall` that performs the correct removal of the service by calling prunsrv.exe for the service name I specify.

**Comment by kares** [comment]
PRs are welcome !

**Comment by driehle** [comment]
Well... here is a basic implementation:
https://github.com/driehle/trinidad_init_services/commit/b3d38e2220e9d295c8c9bf2a9a6f60c0bd77e885

It's not perfect as there is some code that exists twice and that should be refactored in a Helper-Class or so. Additionally it would be cool to support something "service_name"-like on Unix, maybe by creating an init.d file like "trinidad-my-service-name". However, I currently don't have the time to implement that.
