### ISSUE TITLE
Missing configuration options for Windows

### ISSUE THREAD

**Issue by inbox256** [trinidad/trinidad_init_services#32]
The Windows configuration needs to include the services parameters below at a minimum, although ideally it would support all available prunsrv.exe options:

LogPath, LogLevel, Classpath, Jvm, ServiceUser,  ServicePassWord, Startup

Furthermore, it would be nice if Classpath supported ++Classpath, so that an individual jar can be added.

**Comment by kares** [comment]
some of those are in for **1.3.0** ... thanks!
