### ISSUE TITLE
Unable to start service on CentOS 6.3

### ISSUE THREAD

**Issue by KaptajnKold** [trinidad/trinidad_init_services#33]
When I try to start the service with `> sudo service trinidad_my_app start` I get:

```
Starting trinidad daemon...
16/01/2013 13:05:31 25489 jsvc error: Invalid option -procname
16/01/2013 13:05:31 25489 jsvc error: Cannot parse command line arguments
```

If I remove the `-procname` argument from `JSVC_ARGS` in the daemon script and try again, I get (from the log file):

```
16/01/2013 13:32:55 25827 jsvc.exec error: syscall failed in set_caps
16/01/2013 13:32:55 25827 jsvc.exec error: set_caps(CAPS) failed
16/01/2013 13:32:55 25826 jsvc.exec error: Service exit with a return value of 4
```

I'm not sure what version of jsvc is installed, as `> jsvc -version` strangely results in:

```
16/01/2013 13:38:41 25863 jsvc error: No class specified
16/01/2013 13:38:41 25863 jsvc error: Cannot parse command line arguments
```

I can however say that it is the latest version from the CentOS base repository. The package name is `jakarta-commons-daemon-jsvc` and its version is `1:1.0.1-8.9.el6`

**Comment by kares** [comment]
Hey Kaptajn, that's a bit old version - maybe try uninstalling it (if you can) and re-generating the script (it will try to compile jsvc for you using the bundled sources). Or even better, to keep things clean, you may compile it down from the sources yourself and than point to the compiled jsvc binary in the init.d script ... see https://github.com/trinidad/trinidad_init_services/wiki/Installing-JSVC
