### ISSUE TITLE
Daemon wont start after a machine restart

### ISSUE THREAD

**Issue by w1150n** [trinidad/trinidad_init_services#34]
After halting the machine and booting it back up, not only does the service not start on boot, but attempting to start it with "/etc/init.d/trinidad start" produces an error:

[out :: localhost] Pidfile already exists, not starting.

Running "/etc/init.d/trinidad stop" and then "/etc/init.d/trinidad start" doesn't work either.  

The pid file has to manually be deleted before the service starts properly.  This can't be the way it's supposed to work, is it?

**Comment by kares** [comment]
the (trinidad) daemon probably was not shutdown correctly on halt.
you can improve the generated init.d script to check for a given proces name and if not found delete the pid ...
forcing a start when the pid is there (and another instance is running) would be worse than deleting the pid by hand.

**Comment by w1150n** [comment]
I'll give that a shot and let you know, it seems like this is something that should be baked into this gem...

**Comment by arturtr** [comment]
Please merge this pull request into gem

**Comment by kares** [comment]
on master as https://github.com/trinidad/trinidad_init_services/commit/5c4b707c46c0b9ffcd6934f74655a647378c5104 from #36 thank you so much and sorry for the delay!
