### ISSUE TITLE
Jruby 1.7.4 JDK 7u40 CentOS x64 RVM 1.22.2 - Won't serve my app

### ISSUE THREAD

**Issue by twiz718** [trinidad/trinidad_init_services#37]
[capistrano@threatservices trinidad]$ cat trinidad.log
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /home/capistrano/.rvm/rubies/jruby-1.7.4/lib/native/arm-Linux/libjffi-1.2.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

2014     16350  0.0  0.0   8328   392 ?        Ss   13:43   0:00 jsvc-trinidad -home /usr/java/jdk1.7.0_40/jre -wait 20 -pidfile /home/capistrano/trinidad/trinidad.pid -procname jsvc-trinidad -jvm server -outfile /home/capistrano/trinidad/trinidad.log -errfile &1 -cp /home/capistrano/.rvm/gems/jruby-1.7.4/gems/trinidad_init_services-1.2.3/trinidad-libs/jruby-jsvc.jar:/home/capistrano/.rvm/gems/jruby-1.7.4/gems/trinidad_init_services-1.2.3/trinidad-libs/commons-daemon.jar:/home/capistrano/.rvm/rubies/jruby-1.7.4/lib/jruby.jar -Djruby.shell=/bin/sh -Djffi.boot.library.path=/home/capistrano/.rvm/rubies/jruby-1.7.4/lib/native/arm-Linux:/home/capistrano/.rvm/rubies/jruby-1.7.4/lib/native/i386-Linux:/home/capistrano/.rvm/rubies/jruby-1.7.4/lib/native/x86_64-Linux -Djruby.home=/home/capistrano/.rvm/rubies/jruby-1.7.4 -Djruby.lib=/home/capistrano/.rvm/rubies/jruby-1.7.4/lib -Djruby.script=jruby -Djruby.daemon.module.name=Trinidad -Djruby.compat.version=RUBY1_9 -Xmx750m -Xss2048k -Xbootclasspath/a:/home/capistrano/.rvm/rubies/jruby-1.7.4/lib/jruby.jar -Dfile.encoding=UTF-8 com.msp.jsvc.JRubyDaemon /home/capistrano/.rvm/gems/jruby-1.7.4/gems/trinidad_init_services-1.2.3/lib/trinidad/daemon.rb -f /home/capistrano/trinidad/trinidad_config.yml
2014     16351  177  3.5 2113972 283584 ?      Sl   13:43   0:14 jsvc-trinidad -home /usr/java/jdk1.7.0_40/jre -wait 20 -pidfile /home/capistrano/trinidad/trinidad.pid -procname jsvc-trinidad -jvm server -outfile /home/capistrano/trinidad/trinidad.log -errfile &1 -cp /home/capistrano/.rvm/gems/jruby-1.7.4/gems/trinidad_init_services-1.2.3/trinidad-libs/jruby-jsvc.jar:/home/capistrano/.rvm/gems/jruby-1.7.4/gems/trinidad_init_services-1.2.3/trinidad-libs/commons-daemon.jar:/home/capistrano/.rvm/rubies/jruby-1.7.4/lib/jruby.jar -Djruby.shell=/bin/sh -Djffi.boot.library.path=/home/capistrano/.rvm/rubies/jruby-1.7.4/lib/native/arm-Linux:/home/capistrano/.rvm/rubies/jruby-1.7.4/lib/native/i386-Linux:/home/capistrano/.rvm/rubies/jruby-1.7.4/lib/native/x86_64-Linux -Djruby.home=/home/capistrano/.rvm/rubies/jruby-1.7.4 -Djruby.lib=/home/capistrano/.rvm/rubies/jruby-1.7.4/lib -Djruby.script=jruby -Djruby.daemon.module.name=Trinidad -Djruby.compat.version=RUBY1_9 -Xmx750m -Xss2048k -Xbootclasspath/a:/home/capistrano/.rvm/rubies/jruby-1.7.4/lib/jruby.jar -Dfile.encoding=UTF-8 com.msp.jsvc.JRubyDaemon /home/capistrano/.rvm/gems/jruby-1.7.4/gems/trinidad_init_services-1.2.3/lib/trinidad/daemon.rb -f /home/capistrano/trinidad/trinidad_config.yml

This started happening after I upgraded to JDK 7u40 from 7u25...
I changed the value inside my trinidad script to reflect the new path for 7u40 as you can see the process is running but I get nothing in my app's production.log and all requests to HTTP fail with this:

[capistrano@threatservices trinidad]$ telnet 0 80
Trying 0.0.0.0...
Connected to 0.
Escape character is '^]'.
GET / HTTP/1.1   

HTTP/1.1 400 Bad Request
Server: Apache-Coyote/1.1
Transfer-Encoding: chunked
Date: Wed, 11 Sep 2013 19:44:15 GMT
Connection: close

0

Connection closed by foreign host.

**Comment by ghost** [comment]
@twiz718 any resolution on this?

**Comment by twiz718** [comment]
the resolution at the time was to downgrade to jdk 7u25, i believe it should be resolved in newer version of jruby. try 1.7.8...
