### ISSUE TITLE
Exception in thread "jsvc-daemon-main" uninitialized constant Trinidad::CommandLineParser

### ISSUE THREAD

**Issue by jordanvs** [trinidad/trinidad_init_services#39]
Hi there. I'm using RVM with gemsets, running on Ubuntu as a non-root user. My logs output the following error when using the start command:

```
Exception in thread "jsvc-daemon-main" org.jruby.exceptions.RaiseException: (NameError) uninitialized constant Trinidad::CommandLineParser
    at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:2690)
    at home.ubuntu.app.shared.bundle.jruby.$1_dot_9.gems.trinidad_init_services_minus_1_dot_2_dot_3.lib.trinidad.daemon.start(/home/ubuntu/app/shared/bundle/jruby/1.9/gems/trinidad_init_services-1.2.3/lib/trinidad/daemon.rb:24)
```

My guess is that my gems aren't being loaded properly but I'm not completely sure since it's looking in the shared bundle path for trinidad_init_services.

When I run `bundle exec /etc/init.d/trinidad start` (just trying it out) I get the following log output:

```
Deploying from /home/ubuntu/app/current as /
Initializing ProtocolHandler ["http-bio-127.0.0.1-3000"]
Error listenerStart
Context [default] startup failed due to previous errors
The web application [default] appears to have started a thread named [Ruby-1-JIT-1] but has failed to stop it. This is very likely to create a memory leak.
The web application [default] appears to have started a thread named [Ruby-1-JIT-2] but has failed to stop it. This is very likely to create a memory leak.
Starting ProtocolHandler ["http-bio-127.0.0.1-3000"]
```

Note the "Error listenerStart", but no other information. When I `curl` localhost:3000, there is no output in this case.

I'm not sure where to go from here. Any advice?

**Comment by kares** [comment]
how does gem list look ? what trinidad verdion dois it give you. (make sure you set the env similar to the init.d script to check those)

**Comment by jordanvs** [comment]
Thanks @kares after some more debugging I realized that my application had a .ruby-version and .ruby-gemset file included in its root folder. This was causing the gems and even ruby version to be set to 1.9.3 (which didn't exist on my system even) and a gemset that also didn't exist.

I am still seeing the `Error listenerstart` error in the logs however and curl commands yield no response. I will open another ticket/question for this.
