### ISSUE TITLE
Service won't start if installed on certain paths

### ISSUE THREAD

**Issue by adritha84** [trinidad/trinidad_init_services#4]
We have a Rails application that must run as a Windows service.
After I set up the environment variables and the database, I install the service using

jruby -S trinidad_init_service

I enter the required parameters (application path, service name etc.).
Everything works ok with most of the application paths, but there are exceptions (explanations below).

I am testing the application on Windows Server 2008 and Windows Server 2008 R2.
jruby 1.6.3 (ruby-1.8.7-p330) (Java HotSpot(TM) Client VM 1.6.0_26 [Windows Server 2008 R2-x86-java]

The problem appears when the application is placed in certain folders (from what I have tested so far, some of these paths are "C:\IT Solutions\Application", "C:\CT Solutions\Application", "C:\My Solutions\Application"). 
So, if I place my application one of those folder and then install the service using "jruby -S trinidad_init_service", that service won't start, returning "Error 1067: Windows could not start the MyServ service on Local Computer". I have checked the registry, the environment variables, and everything is set up correctly.

This is what I have found in Event Viewer on Windows Server 2008 R2:

"Faulting application name: prunsrv.exe, version: 1.0.5.0, time stamp: 0x4d245a93
Faulting module name: prunsrv.exe, version: 1.0.5.0, time stamp: 0x4d245a93
Exception code: 0xc0000005
Fault offset: 0x00008636
Faulting process id: 0x2e0
Faulting application start time: 0x01cc67c1a105f7f6
Faulting application path: C:\IT Solutions\Application\JRuby\jruby-1.6.3\lib\ruby\gems\1.8\gems\trinidad_init_services-1.0.0\trinidad-libs\prunsrv.exe
Faulting module path: C:\IT Solutions\Application\JRuby\jruby-1.6.3\lib\ruby\gems\1.8\gems\trinidad_init_services-1.0.0\trinidad-libs\prunsrv.exe
Report Id: df48b7f6-d3b4-11e0-8286-000c29659c63"

From what I have seen researching, the exception code is for "access violation".

NOTE: 1. At a certain point I thought it was a matter of spaces in the application path, but the service starts without error with paths like "C:\Program Files (x86)\Application" etc. 
2. For example, if I place the application in "C:\ITSolutions\Application" or "C:\Application", the service has no problem starting and working. 
This is why we expect the service to work with paths like "C:\IT Solutions\Application", "C:\CT Solutions\Application", "C:\My Solutions\Application".

**Comment by calavera** [comment]
I'm actually surprised that we hadn't got any path issue on windows yet :D

@adritha84 can you run this on an irb session launched from the lib directory of the gem:

``` ruby
File.expand_path('../../../trinidad-libs', __FILE__)
```

if you've installed JRuby on C:\, run irb from C:\JRuby\jruby-1.6.3\lib\ruby\gems\1.8\gems\trinidad_init_services-1.0.0\lib\trinidad_init_services. Those slashes can be the cause of the problem but I don't have a windows installation available now to test this.

Thank you!

**Comment by adritha84** [comment]
Ok.
I have JRuby installed in "C:\IT Solutions\Application\JRuby".
I have done what you told me:
1. went to  "C:\IT Solutions\Application\JRuby\jruby-1.6.3\lib\ruby\gems\1.8\gems\trinidad_init_services-1.0.0\"
2. irb(main):001:0>File.expand_path('trinidad-libs', **FILE**)
3. The result is: 
   "C:/IT Solutions/Application/JRuby/jruby-1.6.3/lib/ruby/gems/1.8/gems/trinidad_init_services-1.0.0/(irb)/trinidad_libs"

**Comment by calavera** [comment]
Wait, I think I just gave you a wrong code :)

trinidad-libs should be at "C:\, run irb from C:\JRuby\jruby-1.6.3\lib\ruby\gems\1.8\gems\trinidad_init_services-1.0.0\trinidad-libs"

maybe it should be:

``` ruby
File.expand_path('../../trinidad-libs', __FILE__)
```

**Comment by adritha84** [comment]
```
irb(main):012:0> Dir.getwd
=> "C:/IT Solutions/gislog/JRuby/jruby-1.6.3/lib/ruby/gems/1.8/gems/trinidad_ini
t_services-1.0.0/lib/trinidad_init_services"
irb(main):013:0> File.expand_path('../../trinidad-libs', __FILE__)
=> "C:/IT Solutions/gislog/JRuby/jruby-1.6.3/lib/ruby/gems/1.8/gems/trinidad_ini
t_services-1.0.0/lib/trinidad-libs"
```

**Comment by kares** [comment]
this was probably caused by missing path quoting (on Windows) ... should be fine in recent versions!
