### ISSUE TITLE
syntax error in generated file

### ISSUE THREAD

**Issue by davidhq** [trinidad/trinidad_init_services#43]
With latest version of the gem (1.3.0) the file that is generated contains a sytax error:

```
$ sudo /etc/init.d/trinidad_lr start
/etc/init.d/trinidad_lr: line 119: syntax error near unexpected token `else'
/etc/init.d/trinidad_lr: line 119: `    else'
```

line in questions with context:

```
if case ${JAVA_OPTS} in *"-${opt}"*) true;; *) false;; esac ; then
  # JAVA_OPTS contains option - do no thing
else # <<-- [119]
  if [ "${opt}" == "Xmx" ] ; then
```

another curious thing is that after it generated the file it suggested me to run `update-rc.d -f trinidad remove` ...

**Comment by kares** [comment]
Thanks David, sorry about that - seems as a regression since 1.2 ... will take me a while to get into fixing (adding a spec) this. If you care open a PR. For completeness please provide your OS/shell details. Thanks!
