### ISSUE TITLE
Unable To Load trinidad_logging_extensions

### ISSUE THREAD

**Issue by jordanyaker** [trinidad/trinidad_init_services#45]
Everything is working great with the current install out of the box - with the exception of logging extensions.  Whenever I attempt to launch an instance with logging extensions enabled, I end up with the following message:

```
Failed to load the :logging extension (no such file to load -- trinidad_logging_extension) 
```

I have the gem installed globally and locally within my project yet somehow, the daemon is unable to find it.

Any help would be appreciated.

**Comment by kares** [comment]
its been a while since I've been involved (not sure I can help) - try to provide more details:
- what kind of app + is the extension part of the bundle
- any customizations to the jsvc generated /etc/init.d file on Linux?
- are there any other extensions you're using that are loading fine?
- trinidad version + your trinidad configuration

**Comment by jordanyaker** [comment]
Please see my answers as follows:
- It's a Sinatra app and I was trying to load the logging extension.
- Correct
- The logging extension was my only extension.  However, even when the
  app started I was getting a Rack error. I'm thinking this pointed to a
  larger issue with the loading of my gems for the project.

**Comment by kares** [comment]
definitely smt about the generated `GEM_HOME` than ... next time try to answer all questions :) gd luck !

**Comment by jordanyaker** [comment]
Ugh, I'm so sorry.  I didn't realize that sent.  I was writing that e-mail in my car at the gas station and I was going to get you my Trinidad config.  Unfortunately I had a lot of fires to fight and hadn't been able to get back to this until this morning.  Trinidad is 1.4.6.  Still interested in the config?  Or this is the GEM_HOME in the init.d script?

**Comment by kares** [comment]
was the extension gem correctly installed under the init.d script's GEM_HOME, no RVM interference ?

**Comment by jordanyaker** [comment]
Is RVM a known interferer?  I am using RVM with the project.  

Additionally, since this was an init.d script, I installed it in `/etc/init.d`.  Is there documentation that says the script should be installed in GEM_HOME?  If so, that's my fault; I completely missed it.

**Comment by kares** [comment]
yes anything changing GEM_HOME/GEM_PATH might interfere, really depends on how/whether RVM will be loaded when starting an init.d daemon. due this I was asking to confirm whether under the GEM_HOME path (from the init.d script) the extension gem is correctly installed. also check whether GEM_PATH is not messing e.g. echo it somewhere as the init.d script is run.

**Comment by jordanyaker** [comment]
@kares I'll have to check that out and post my results.

**Comment by jordanyaker** [comment]
@kares I finally was able to take some time and get back on this.  It was related to the path and I was able to get it working.  However, I think it's worth noting that most deployments are going to deploy gems to the application's `vendor/bundle` directory.
